const PIXEL_SIZE = 15;
const VIEWPORT_WIDTH = window.innerWidth;
const VIEWPORT_HEIGHT = window.innerHeight;
const DRAWING_COLUMNS = 32;
const DRAWING_ROWS = 32;
const DRAWING_WIDTH = PIXEL_SIZE * DRAWING_COLUMNS;
const DRAWING_HEIGHT = PIXEL_SIZE * DRAWING_ROWS;
const CANVAS_WIDTH = Math.floor(VIEWPORT_WIDTH * .8);
const TOOLBAR_WIDTH = Math.floor(VIEWPORT_WIDTH * .2);
module.exports = {
    PIXEL_SIZE,
    SECONDARY_COLOR: '#414141',
    CANVAS_WIDTH,
    TOOLBAR_WIDTH,
    DRAWING_COLUMNS,
    DRAWING_ROWS,
    DRAWING_WIDTH,
    DRAWING_HEIGHT,
    VIEWPORT_WIDTH,
    VIEWPORT_HEIGHT,
    DRAWING_OFFSET_LEFT: Math.round(VIEWPORT_WIDTH / 2),
    DRAWING_OFFSET_TOP: Math.round(VIEWPORT_HEIGHT / 2 - ((DRAWING_ROWS * PIXEL_SIZE) / 2)),
};